services:
  wp:
    image: wordpress
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_NAME=wpdb
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=wppass
      - WORDPRESS_DB_HOST=db
  db:
    image: mysql
    volumes:
      - db_sql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootPassword12
      - MYSQL_DATABASE=wpdb
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=wppass 
volumes:
  db_sql: